"""Zone transfer (AXFR) from the pdns DNS listener — used by the "view
zone" feature to show a zone exactly as a secondary receives it. Goes over
the real DNS transfer path (TSIG and all), so a failure here means the
secondaries cannot transfer either."""

import socket

import dns.exception
import dns.name
import dns.query
import dns.rdatatype
import dns.tsigkeyring
import dns.xfr
import dns.zone

from .config import settings


class AxfrError(Exception):
    pass


def axfr_text(zone: str) -> tuple[str, int]:
    """Transfer `zone` and return (zone file text, record count)."""
    s = settings()
    try:
        addr = socket.getaddrinfo(s.pdns_axfr_host, None)[0][4][0]
    except socket.gaierror as e:
        raise AxfrError(f"cannot resolve {s.pdns_axfr_host}: {e}")

    kw = {}
    if s.tsig_key and s.tsig_secret:
        kw = {
            "keyring": dns.tsigkeyring.from_text({s.tsig_key: s.tsig_secret}),
            "keyname": dns.name.from_text(s.tsig_key),
            "keyalgorithm": dns.name.from_text(s.tsig_algo),
        }
    try:
        xfr = dns.query.xfr(addr, zone, port=s.pdns_axfr_port, timeout=10, lifetime=30,
                            relativize=False, **kw)
        z = dns.zone.from_xfr(xfr, relativize=False)
    except dns.xfr.TransferError as e:
        raise AxfrError(f"transfer refused: {e}")
    except dns.exception.FormError as e:
        raise AxfrError(f"malformed transfer: {e}")
    except (dns.exception.Timeout, OSError) as e:
        raise AxfrError(f"cannot reach {addr}:{s.pdns_axfr_port}: {e}")
    except Exception as e:  # tsig errors etc.
        raise AxfrError(str(e))

    text = z.to_text(sorted=True, relativize=False)
    count = sum(len(rds) for _, rds in z.iterate_rdatasets())
    return text, count


class ZoneParseError(Exception):
    pass


def _detect_origin(text: str) -> str | None:
    """Origin of a zone file = owner name of its SOA record (or $ORIGIN)."""
    for line in text.splitlines():
        parts = line.split()
        if not parts or line.startswith(";"):
            continue
        if parts[0] == "$ORIGIN" and len(parts) > 1:
            return parts[1]
        if "SOA" in parts[1:5] and not parts[0].startswith("$"):
            return parts[0]
    return None


def parse_zone_text(text: str, name: str | None) -> tuple[str, list[dict]]:
    """Parse exported zone text into (origin, pdns rrsets).

    If `name` differs from the file's own origin, the zone is re-rooted:
    owner names and in-zone record data are rewritten to the new origin
    (out-of-zone absolute names are kept as-is) — i.e. importing under a
    new name clones the zone.
    """
    detected = _detect_origin(text)
    origin = (name or detected or "").strip()
    if not origin:
        raise ZoneParseError("cannot determine the zone name — no SOA found; "
                             "fill in the zone name field")
    origin = origin.rstrip(".") + "."
    parse_origin = detected or origin
    try:
        z = dns.zone.from_text(text, origin=parse_origin, relativize=True,
                               check_origin=True)
    except dns.exception.DNSException as e:
        raise ZoneParseError(f"zone file does not parse: {e}")

    new_origin = dns.name.from_text(origin)
    by_key: dict[tuple[str, str], dict] = {}
    for node_name, rdataset in z.iterate_rdatasets():
        rtype = dns.rdatatype.to_text(rdataset.rdtype)
        if rtype in ("RRSIG", "NSEC", "NSEC3", "NSEC3PARAM", "DNSKEY"):
            continue  # DNSSEC material is regenerated by the server, not imported
        abs_name = node_name.derelativize(new_origin).to_text().lower()
        rr = by_key.setdefault(
            (abs_name, rtype),
            {"name": abs_name, "type": rtype, "ttl": rdataset.ttl,
             "changetype": "REPLACE", "records": []},
        )
        for rdata in rdataset:
            content = rdata.to_text(origin=new_origin, relativize=False)
            if not any(r["content"] == content for r in rr["records"]):
                rr["records"].append({"content": content, "disabled": False})
    if (origin, "SOA") not in by_key:
        raise ZoneParseError("no SOA record at the zone apex")
    return origin, list(by_key.values())
