#!/bin/sh
# nsd-catalog-sync.sh — catalog-zone autoconfiguration for OLD NSD (< 4.9.0)
# that has no native `catalog: consumer` support. Plain POSIX shell (bash,
# dash, FreeBSD /bin/sh). Successor of the old nsd_config_generator.sh.
#
# It AXFRs the catalog zone from the hidden master (dig or drill), extracts
# the member zones from the RFC 9432 PTR records, regenerates an nsd.conf
# include file with one secondary-zone stanza per member, and reloads NSD
# via nsd-control reconfig — but only when the zone list actually changed.
#
# One-time setup on the slave:
#   1. add to /etc/nsd/nsd.conf:
#          include: "/etc/nsd/zones.catalog.conf"
#      (plus a key: block if you use TSIG — see nsd.conf.example)
#   2. touch /etc/nsd/zones.catalog.conf  (must exist for nsd to start)
#   3. cron:  */5 * * * * /usr/local/bin/nsd-catalog-sync.sh
#
# Usage: nsd-catalog-sync.sh [config-file]
#        (default config: /usr/local/etc/nsd-catalog-sync.conf; environment
#         variables override the config file)
#
# Exit codes: 0 = in sync (changed or not), 1 = error (old config kept).

# ---- configuration: environment > config file > defaults -------------------
e_MASTER="${MASTER:-}";           e_MASTER_PORT="${MASTER_PORT:-}"
e_CATALOG="${CATALOG:-}";         e_ZONES_CONF="${ZONES_CONF:-}"
e_NSD_CONF="${NSD_CONF:-}";       e_NSD_CONTROL="${NSD_CONTROL:-}"
e_TSIG_NAME="${TSIG_NAME:-}";     e_TSIG_ALGO="${TSIG_ALGO:-}"
e_TSIG_SECRET="${TSIG_SECRET:-}"; e_QUIET="${QUIET:-}"

CONF="${1:-/usr/local/etc/nsd-catalog-sync.conf}"
[ -f "$CONF" ] && . "$CONF"

MASTER="${e_MASTER:-${MASTER:-}}"
MASTER_PORT="${e_MASTER_PORT:-${MASTER_PORT:-53}}"
CATALOG="${e_CATALOG:-${CATALOG:-catalog.mojodns}}"
ZONES_CONF="${e_ZONES_CONF:-${ZONES_CONF:-/etc/nsd/zones.catalog.conf}}"
NSD_CONF="${e_NSD_CONF:-${NSD_CONF:-/etc/nsd/nsd.conf}}"
NSD_CONTROL="${e_NSD_CONTROL:-${NSD_CONTROL:-nsd-control}}"
TSIG_NAME="${e_TSIG_NAME:-${TSIG_NAME:-}}"
TSIG_ALGO="${e_TSIG_ALGO:-${TSIG_ALGO:-hmac-sha256}}"
TSIG_SECRET="${e_TSIG_SECRET:-${TSIG_SECRET:-}}"
QUIET="${e_QUIET:-${QUIET:-false}}"

log() { [ "$QUIET" = "true" ] || echo "nsd-catalog-sync: $*"; }
err() { echo "nsd-catalog-sync: ERROR: $*" >&2; }

[ -n "$MASTER" ] || { err "MASTER is not set"; exit 1; }
CATALOG="$(printf '%s' "$CATALOG" | sed 's/\.$//')"

KEYREF="NOKEY"
[ -n "$TSIG_NAME" ] && [ -n "$TSIG_SECRET" ] && KEYREF="$TSIG_NAME"

# ---- transfer the catalog zone ----------------------------------------------
if command -v dig >/dev/null 2>&1; then
    if [ "$KEYREF" = "NOKEY" ]; then
        axfr=$(dig +tcp +noall +answer -p "$MASTER_PORT" "@$MASTER" "$CATALOG." AXFR)
    else
        axfr=$(dig +tcp +noall +answer -p "$MASTER_PORT" \
                   -y "$TSIG_ALGO:$TSIG_NAME:$TSIG_SECRET" \
                   "@$MASTER" "$CATALOG." AXFR)
    fi
elif command -v drill >/dev/null 2>&1; then
    if [ "$KEYREF" = "NOKEY" ]; then
        axfr=$(drill -p "$MASTER_PORT" -t axfr "$CATALOG." "@$MASTER" | grep -v '^;')
    else
        axfr=$(drill -p "$MASTER_PORT" -y "$TSIG_NAME:$TSIG_SECRET:$TSIG_ALGO" \
                     -t axfr "$CATALOG." "@$MASTER" | grep -v '^;')
    fi
else
    err "neither dig nor drill found"; exit 1
fi

# a successful AXFR always carries the catalog SOA; anything else is failure
if ! printf '%s\n' "$axfr" | awk 'toupper($4)=="SOA"{found=1} END{exit !found}'; then
    err "catalog transfer from $MASTER:$MASTER_PORT failed (check TSIG/ACL)"
    exit 1
fi

version=$(printf '%s\n' "$axfr" | awk -v v="version.$CATALOG." \
          'tolower($1)==v && toupper($4)=="TXT"{gsub(/"/,"",$5); print $5; exit}')
[ "$version" = "2" ] || log "warning: catalog schema version is '${version:-?}', expected 2"

zones=$(printf '%s\n' "$axfr" | awk -v cat=".zones.$CATALOG." \
        'toupper($4)=="PTR" && index(tolower($1), cat) {sub(/\.$/,"",$5); print tolower($5)}' \
        | sort -u)

# ---- regenerate the include file -------------------------------------------
tmp="$ZONES_CONF.tmp.$$"
{
    echo "# generated by nsd-catalog-sync.sh from catalog zone '$CATALOG' — do not edit"
    for z in $zones; do
        printf 'zone:\n    name: "%s"\n    allow-notify: %s %s\n    request-xfr: AXFR %s@%s %s\n' \
               "$z" "$MASTER" "$KEYREF" "$MASTER" "$MASTER_PORT" "$KEYREF"
    done
} > "$tmp"

if [ -f "$ZONES_CONF" ] && cmp -s "$tmp" "$ZONES_CONF"; then
    rm -f "$tmp"
    log "no changes ($(printf '%s\n' "$zones" | grep -c .) zones)"
    exit 0
fi

# validate before activating: nsd-checkconf parses nsd.conf incl. includes,
# so check against a copy of the real config with the include swapped in
if command -v nsd-checkconf >/dev/null 2>&1 && [ -f "$NSD_CONF" ]; then
    if ! nsd-checkconf "$NSD_CONF" >/dev/null 2>&1; then
        log "warning: current $NSD_CONF does not validate; proceeding anyway"
    fi
fi

old_count=0
[ -f "$ZONES_CONF" ] && old_count=$(grep -c '^zone:' "$ZONES_CONF")
mv "$tmp" "$ZONES_CONF"
new_count=$(grep -c '^zone:' "$ZONES_CONF")

if command -v nsd-checkconf >/dev/null 2>&1 && ! nsd-checkconf "$NSD_CONF" >/dev/null 2>&1; then
    err "$NSD_CONF fails validation after update — NSD not reloaded, inspect $ZONES_CONF"
    exit 1
fi

if ! "$NSD_CONTROL" reconfig >/dev/null 2>&1; then
    err "'$NSD_CONTROL reconfig' failed — config updated but NSD not reloaded"
    exit 1
fi

log "zone list updated: $old_count -> $new_count zones, NSD reloaded"
exit 0
