#!/bin/sh
# nsd-catalog-sync.sh — catalog-zone autoconfiguration for a shared NSD.
#
# Two uses:
#   * NSD < 4.9.0 that has no native `catalog: consumer` support, and
#   * ANY NSD that must follow MORE THAN ONE catalog at once — NSD natively
#     allows only a single catalog consumer zone, so to share one NSD across
#     several mojodns installations you aggregate their catalogs here.
#
# It AXFRs each catalog zone (dig or drill), extracts the member zones from
# the RFC 9432 PTR records, regenerates an nsd.conf include file with one
# secondary-zone stanza per member (pointing request-xfr/allow-notify at the
# master that catalog came from), and runs `nsd-control reconfig` — but only
# when the combined zone list actually changed.
#
# Plain POSIX shell (bash, dash, FreeBSD /bin/sh). Successor of the old
# nsd_config_generator.sh.
#
# --- single source --------------------------------------------------------
# config: /usr/local/etc/nsd-catalog-sync.conf (MASTER/CATALOG/TSIG_*),
# environment overrides it. See nsd-catalog-sync.conf.example.
#
# --- multiple sources (shared NSD) ----------------------------------------
# set SOURCES_DIR (default /usr/local/etc/nsd-catalog-sync.d); every *.conf
# in it describes one mojodns installation (its MASTER/CATALOG/TSIG_*). The
# zone lists from all of them are merged into one include file. Global
# settings (ZONES_CONF/NSD_CONF/NSD_CONTROL/QUIET) still come from the main
# config / environment.
#
# One-time NSD setup:
#   1. nsd.conf:  include: "/etc/nsd/zones.catalog.conf"
#                 (+ a key: block per TSIG key used by any source)
#   2. touch /etc/nsd/zones.catalog.conf   (must exist before nsd starts)
#   3. cron:  */5 * * * * /usr/local/bin/nsd-catalog-sync.sh
#
# Usage: nsd-catalog-sync.sh [config-file]
# Exit:  0 = in sync (changed or not); 1 = error (existing config kept).

# ---- global configuration: environment > config file > defaults ------------
e_ZONES_CONF="${ZONES_CONF:-}";   e_NSD_CONF="${NSD_CONF:-}"
e_NSD_CONTROL="${NSD_CONTROL:-}"; e_QUIET="${QUIET:-}"
e_SOURCES_DIR="${SOURCES_DIR:-}"

CONF="${1:-/usr/local/etc/nsd-catalog-sync.conf}"
[ -f "$CONF" ] && . "$CONF"

ZONES_CONF="${e_ZONES_CONF:-${ZONES_CONF:-/etc/nsd/zones.catalog.conf}}"
NSD_CONF="${e_NSD_CONF:-${NSD_CONF:-/etc/nsd/nsd.conf}}"
NSD_CONTROL="${e_NSD_CONTROL:-${NSD_CONTROL:-nsd-control}}"
QUIET="${e_QUIET:-${QUIET:-false}}"
SOURCES_DIR="${e_SOURCES_DIR:-${SOURCES_DIR:-/usr/local/etc/nsd-catalog-sync.d}}"

log() { [ "$QUIET" = "true" ] || echo "nsd-catalog-sync: $*"; }
err() { echo "nsd-catalog-sync: ERROR: $*" >&2; }

command -v dig >/dev/null 2>&1 || command -v drill >/dev/null 2>&1 || {
    err "neither dig nor drill found"; exit 1; }

tmp="$ZONES_CONF.tmp.$$"
seen="$tmp.seen"
: > "$tmp"; : > "$seen"
trap 'rm -f "$tmp" "$seen"' EXIT
echo "# generated by nsd-catalog-sync.sh — do not edit" > "$tmp"

FAIL=0

# transfer one catalog and append its member stanzas to $tmp.
# args: master port catalog tsig_name tsig_algo tsig_secret label
process_source() {
    s_master="$1"; s_port="${2:-53}"; s_catalog="$3"
    s_tname="$4"; s_talgo="${5:-hmac-sha256}"; s_tsecret="$6"; s_label="$7"

    [ -n "$s_master" ]  || { err "[$s_label] MASTER not set"; FAIL=1; return 1; }
    [ -n "$s_catalog" ] || { err "[$s_label] CATALOG not set"; FAIL=1; return 1; }
    s_catalog="$(printf '%s' "$s_catalog" | sed 's/\.$//')"

    s_keyref="NOKEY"
    [ -n "$s_tname" ] && [ -n "$s_tsecret" ] && s_keyref="$s_tname"

    if command -v dig >/dev/null 2>&1; then
        if [ "$s_keyref" = "NOKEY" ]; then
            axfr=$(dig +tcp +noall +answer -p "$s_port" "@$s_master" "$s_catalog." AXFR 2>/dev/null)
        else
            axfr=$(dig +tcp +noall +answer -p "$s_port" \
                       -y "$s_talgo:$s_tname:$s_tsecret" \
                       "@$s_master" "$s_catalog." AXFR 2>/dev/null)
        fi
    else
        if [ "$s_keyref" = "NOKEY" ]; then
            axfr=$(drill -p "$s_port" -t axfr "$s_catalog." "@$s_master" 2>/dev/null | grep -v '^;')
        else
            axfr=$(drill -p "$s_port" -y "$s_tname:$s_tsecret:$s_talgo" \
                         -t axfr "$s_catalog." "@$s_master" 2>/dev/null | grep -v '^;')
        fi
    fi

    # a successful AXFR always carries the catalog SOA
    if ! printf '%s\n' "$axfr" | awk 'toupper($4)=="SOA"{f=1} END{exit !f}'; then
        err "[$s_label] catalog transfer of '$s_catalog' from $s_master:$s_port failed (check TSIG/ACL/reachability)"
        FAIL=1; return 1
    fi

    version=$(printf '%s\n' "$axfr" | awk -v v="version.$s_catalog." \
              'tolower($1)==v && toupper($4)=="TXT"{gsub(/"/,"",$5); print $5; exit}')
    [ "$version" = "2" ] || log "[$s_label] warning: catalog schema version '${version:-?}', expected 2"

    zones=$(printf '%s\n' "$axfr" | awk -v cat=".zones.$s_catalog." \
            'toupper($4)=="PTR" && index(tolower($1), cat){sub(/\.$/,"",$5); print tolower($5)}' \
            | sort -u)

    n=0; dup=0
    for z in $zones; do
        if grep -qxF "$z" "$seen"; then
            log "[$s_label] zone '$z' already provided by another source — skipped"
            dup=$((dup + 1)); continue
        fi
        echo "$z" >> "$seen"
        printf 'zone:\n    name: "%s"\n    allow-notify: %s %s\n    request-xfr: AXFR %s@%s %s\n' \
               "$z" "$s_master" "$s_keyref" "$s_master" "$s_port" "$s_keyref" >> "$tmp"
        n=$((n + 1))
    done
    log "[$s_label] $n zones from '$s_catalog' @ $s_master${dup:+ ($dup duplicate(s) skipped)}"
    return 0
}

# ---- gather sources --------------------------------------------------------
nsrc=0
if [ -d "$SOURCES_DIR" ] && ls "$SOURCES_DIR"/*.conf >/dev/null 2>&1; then
    for f in "$SOURCES_DIR"/*.conf; do
        # read this source's settings in isolation
        MASTER=""; MASTER_PORT=""; CATALOG=""
        TSIG_NAME=""; TSIG_ALGO=""; TSIG_SECRET=""
        . "$f"
        process_source "$MASTER" "$MASTER_PORT" "$CATALOG" \
                        "$TSIG_NAME" "$TSIG_ALGO" "$TSIG_SECRET" \
                        "$(basename "$f" .conf)"
        nsrc=$((nsrc + 1))
    done
else
    # single-source mode: settings come from the main config / environment
    process_source "${MASTER:-}" "${MASTER_PORT:-53}" "${CATALOG:-catalog.mojodns}" \
                   "${TSIG_NAME:-}" "${TSIG_ALGO:-hmac-sha256}" "${TSIG_SECRET:-}" \
                   "single"
    nsrc=1
fi

[ "$nsrc" -gt 0 ] || { err "no sources configured"; exit 1; }

# If ANY source failed, do NOT touch the live config — otherwise an
# unreachable master would silently drop all of its zones from NSD.
if [ "$FAIL" -ne 0 ]; then
    err "one or more sources failed — keeping existing $ZONES_CONF unchanged"
    exit 1
fi

# ---- activate only on change -----------------------------------------------
if [ -f "$ZONES_CONF" ] && cmp -s "$tmp" "$ZONES_CONF"; then
    log "no changes ($(grep -c '^zone:' "$tmp") zones from $nsrc source(s))"
    exit 0
fi

old_count=0
[ -f "$ZONES_CONF" ] && old_count=$(grep -c '^zone:' "$ZONES_CONF")
cp "$tmp" "$ZONES_CONF"
new_count=$(grep -c '^zone:' "$ZONES_CONF")

if command -v nsd-checkconf >/dev/null 2>&1 && ! nsd-checkconf "$NSD_CONF" >/dev/null 2>&1; then
    err "$NSD_CONF fails validation after update — NSD not reloaded, inspect $ZONES_CONF"
    exit 1
fi

if ! "$NSD_CONTROL" reconfig >/dev/null 2>&1; then
    err "'$NSD_CONTROL reconfig' failed — config updated but NSD not reloaded"
    exit 1
fi

log "zone list updated: $old_count -> $new_count zones from $nsrc source(s), NSD reloaded"
exit 0
